# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/psf/black
  rev: 23.1a1
  hooks:
  - id: black
    types: [ python ]
- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
  - id: pyupgrade
    args: ["--py37-plus"]
    types: [ python ]
- repo: https://github.com/pycqa/flake8
  rev: 5.0.4  # 6.0.0 requires Python 3.8
  hooks:
  - id: flake8
    types: [ python ]
exclude: |
            (?x)^(
                tests/data|
                tree-sitter-zeek
            )$
